namespace: "netapp"
name: "ontap"
version: "19.12.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license: "GPL-2.0-or-later"
readme: README.md
description: NetApp ONTAP Collection
repository: https://github.com/netapp/ansible/
homepage: netapp.io
tags:
    - "Storage"
