namespace: "netapp"
name: "ontap"
version: "20.2.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license: "GPL-2.0-or-later"
readme: README.md
description: NetApp ONTAP Collection
repository: https://github.com/ansible-collections/ansible_collections_netapp
homepage: netapp.io
tags:
    - storage
